Project structure and jwt
ilisau/qaprotours pull request #1
Opened 2023-02-04 16:33 UTC by kermakovich

2023-02-04 17:06 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/Hotel.java
> +    @ManyToOne
@ManyToOne? Кажется One to one подойдет, ведь для каждого отеля будет создаваться адрес и сетаться ему

2023-02-04 17:08 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/Tour.java
> +    private enum TourType { HEALTH, CULTURE }
Может вынести в отдельный класс? нам понадобится этот енам для поиска туров пользователем

2023-02-04 17:09 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/exception/ResourceDoesNotExistException.java
> +
Это то же самое по логике что и ResourceNotFound? тогда можно выбрать это более короткое название

2023-02-04 17:13 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/jwt/JwtAccess.java
> +
Нам нужно время жизни? Думаю можно просто передавать пару из двух токенов в строках одного класса без лишней вложенности

2023-02-04 17:14 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/user/Passport.java
> +    @ManyToOne
а для чего @Id

2023-02-04 17:19 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/user/UserTour.java
> +    private enum OrderTourStatus { ORDERED, CONFIRMED }
Тоже думаю, что можно вынести в паблик

2023-02-04 17:21 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/jwt/Refresh.java
> +public class Refresh {
Назови как JwtRefresh, чтобы было понятно, что это связано с JwtAccess

2023-02-04 17:23 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/service/impl/AuthServiceImpl.java
> +    }
тут и в других посмотри где строчки в конце не стоят

2023-02-04 17:25 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/service/impl/AuthServiceImpl.java
> +        }
Зачем проверка? Если пользователь сменил пароль, то чтобы его выкинуло из аккаунта?

2023-02-04 17:29 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/service/impl/JwtServiceImpl.java
> +        return jwtUserDetails.getId() != null && jwtUserDetails.getPassword() == null;
что делает метод и для чего он?

2023-02-04 17:33 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/controller/UserController.java
> +@RequiredArgsConstructor
поставь / перед api, может сделать авторизацию и все с этим в AuthController?

2023-02-04 17:34 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/controller/UserController.java
> +    private final RefreshMapper refreshMapper;
Назови тоже как название класса в camelCase

2023-02-04 17:35 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/dto/ErrorDto.java
> +@Schema(description = "dto for errors")
Почему бы не заменить на @Data? в других дто тоже

2023-02-04 17:35 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/dto/onCreate.java
> +
интерфейс с большой буквы

2023-02-04 17:37 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/dto/jwt/AuthenticationDto.java
> +    @Schema(description = "user password")
пароль можно сверху не ограничивать здесь, мы же его хэшируем в строку определенного размера

2023-02-04 17:38 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/mapper/jwt/AuthenticationMapper.java
> +
давай называть все методы в маппере короче - toDto, toEntity

2023-02-04 17:40 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/dto/jwt/JwtResponseDto.java
> +
а зачем другие имена полей? в маппинге можно будет убрать кучу лишних аннотаций и проще разрабатывать новые не задумываясь о том, что какие-то поля имеют другое название. А мапперы сами найдутся для них и без аннотаций

2023-02-04 17:41 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/security/CustomAccessDeniedHandler.java
> +        response.setStatus(HttpServletResponse.SC_FORBIDDEN);
давай это я в лямбду перенесу при конфиге спринга

2023-02-04 17:44 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/web/dto/jwt/AuthenticationDto.java
> +    @Schema(description = "user password")
но в дто это сам пароль, например, "1234", но это по факту от userDto взято

2023-02-04 17:46 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/domain/Hotel.java
> +    @ManyToOne
нужна ли тогда вообще отдельная сущность?

2023-02-04 17:47 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/domain/exception/ResourceDoesNotExistException.java
> +
Богдан сказал так назвать

2023-02-04 17:48 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/domain/user/Passport.java
> +    @ManyToOne
hibernate без этого не может

2023-02-04 17:54 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/service/impl/AuthServiceImpl.java
> +        }
чтобы в этом случае refresh токен считался недействительным

2023-02-04 17:55 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/service/impl/JwtServiceImpl.java
> +        return jwtUserDetails.getId() != null && jwtUserDetails.getPassword() == null;
мы должны удостовреиться, что пользователь послал именно access token, а не, например, refresh. Сделано для того, чтоюы не происходило подмены

2023-02-04 17:59 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/web/controller/UserController.java
> +@RequiredArgsConstructor
для чего ставить /? все работает и без него
насчет AuthController можно, тогда url: api/v1/login  or refresh

2023-02-04 18:09 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/web/security/CustomAccessDeniedHandler.java
> +        response.setStatus(HttpServletResponse.SC_FORBIDDEN);
мне кажется, лучше оставить отдельно, там итак конфиг довольно большой

2023-02-04 18:18 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/web/dto/jwt/AuthenticationDto.java
> +    @Schema(description = "user password")
я вставляла с той точки зрения, что если пароль больше 20 символов, значит он 100% неправильный и мне не нужно лезть в бд, доставать пользователя и тд

2023-02-04 18:43 UTC, ilisau requested changes
1) поменять урл для аутентификации и сократить конфиг секьюрити
2) строка-тип в токенах для различия вида токенов

2023-02-04 18:43 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/Hotel.java
> +    @ManyToOne
Да, адрес может в последствии и кому-нибудь еще добавиться, просто при создании отеля будет создаваться адрес, который будет связан с отелем, чтобы никто кроме этого отеля не мог с ним ничего сделать

2023-02-04 18:43 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/user/Passport.java
> +    @ManyToOne
так давай паспорту дадим айди

2023-02-04 18:43 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/security/CustomAccessDeniedHandler.java
> +        response.setStatus(HttpServletResponse.SC_FORBIDDEN);
ну это просто лишний класс, который как раз таки только в одном месте и вызывается, что так и просит его сделать приватным

2023-02-04 18:43 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/dto/jwt/AuthenticationDto.java
> +    @Schema(description = "user password")
ну просто если я пользователь который боится за безопасность и зарегался с 30 символьным паролем, то я не смогу авторизоваться

2023-02-04 18:43 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/controller/UserController.java
> +@RequiredArgsConstructor
/api/v1/auth/login
/api/v1/auth/refresh
тут же будет регистрация происходить, чтобы мы могли навесить лишь один эндпоинт в permitAll в конфиге секьюрити

2023-02-04 19:05 UTC, kermakovich commented on src/main/java/com/solvd/qaprotours/web/dto/jwt/AuthenticationDto.java
> +    @Schema(description = "user password")
но у меня и на userDto стояло ограничение такое же, так что твой случай не прошел бы

2023-02-06 07:14 UTC, ilisau approved these changes

2023-02-06 07:14 UTC, merged