User service
ilisau/qaprotours pull request #41
Opened 2023-03-07 09:45 UTC by ilisau

2023-03-07 11:05 UTC, h1alexbel reviewed
@ilisau explain these changes, please. Or name pr properly

2023-03-07 11:05 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/UserService.java
>  public interface UserService {
@ilisau 
a better naming is ```UserClient```

2023-03-07 17:10 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/exception/MicroserviceException.java
> +public class MicroserviceException extends RuntimeException {
ErrorDto from UserService (from its ControllerAdvice). I throw it to use ClientErrorDecoder

2023-03-07 18:33 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/exception/MicroserviceException.java
> +public class MicroserviceException extends RuntimeException {
rename it. should be ```ExernalServiceException``` or ```UserServiceException```

2023-03-08 14:29 UTC, h1alexbel requested changes

2023-03-08 14:29 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/exception/MicroserviceException.java
> +public class MicroserviceException extends RuntimeException {
rename it. Make it more specific.

2023-03-09 04:44 UTC, h1alexbel approved these changes

2023-03-09 04:44 UTC, merged