Implement reactivity
ilisau/qaprotours pull request #52
Opened 2023-03-28 12:39 UTC by ilisau

In this PR I implemented reactive approach to monolithic application and close #45

2023-03-28 12:56 UTC, ilisau commented
It is too difficult to change monolithic type to reactive. And some features are not common with JPA and R2DBC

2023-03-28 14:44 UTC, h1alexbel requested changes
@ilisau I believe that JWT logic can be not a reactive one. It's an overhead to use reactive programming everywhere

2023-03-28 14:44 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/tour/Tour.java
>  import jakarta.persistence.*;
don't use wildcard import

2023-03-28 14:44 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/tour/Tour.java
> +@org.springframework.data.relational.core.mapping.Table(name = "tours")
I can't see any import conflicts here. So, why do you using the full class name?

2023-03-28 14:44 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/repository/TicketRepository.java
> +    Flux<Ticket> findAllByTourArrivalTimeIsAfterAndTourArrivalTimeIsBeforeAndStatus(LocalDateTime start, LocalDateTime end, Ticket.Status status);
method is huge, looks bad

2023-03-28 14:44 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/ImageServiceImpl.java
> +
empty lines inside the method is code smell: https://www.yegor256.com/2014/11/03/empty-line-code-smell.html

2023-03-28 14:44 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +        Mono<Tour> error = Mono.error(new ResourceDoesNotExistException("tour with id " + tourId + " does not exist"));
line is too long

2023-03-28 14:44 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/security/expressions/CustomMethodSecurityExpressionRoot.java
> +                .block();
don't use block here

2023-03-28 14:44 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/security/jwt/JwtFilter.java
> +        } catch (JwtException | AuthException ignored) {
group exception catchers is a bad practice: https://www.yegor256.com/2022/08/30/dont-group-exception-catchers.html

2023-03-28 14:44 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/security/jwt/JwtUserDetailsService.java
> +                .block();
don't block here

2023-03-29 07:57 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +        Mono<Tour> error = Mono.error(new ResourceDoesNotExistException("tour with id " + tourId + " does not exist"));
This line is right 120 symbols long, but I can move exception constructor away, is it not redundant?

2023-03-29 08:08 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/repository/TicketRepository.java
> +    Flux<Ticket> findAllByTourArrivalTimeIsAfterAndTourArrivalTimeIsBeforeAndStatus(LocalDateTime start, LocalDateTime end, Ticket.Status status);
It helps to avoid SQL query and use words to describe limitations for objects to be returned

2023-03-29 08:40 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +        Mono<Tour> error = Mono.error(new ResourceDoesNotExistException("tour with id " + tourId + " does not exist"));
> This line is right 120 symbols long, but I can move exception constructor away, is it not redundant?

You can do something like this:
```java
Mono<Tour> error =
 Mono.error(
 new ResourceDoesNotExistException("your message here")
)
```

2023-03-29 09:46 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/tour/Tour.java
> +import jakarta.persistence.AttributeOverride;
why do you using the JPA? it is not reactive. use r2dbc or hibernate-reactive instead

2023-03-29 13:22 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/domain/tour/Tour.java
> +import jakarta.persistence.AttributeOverride;
There are no useful annotation in R2DBC :( https://github.com/spring-projects/spring-data-r2dbc/issues/288 for example

2023-03-29 13:38 UTC, h1alexbel requested changes

2023-03-29 13:38 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/security/expressions/CustomMethodSecurityExpressionRoot.java
> +                .block();
don't block

2023-03-29 13:47 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/security/expressions/CustomMethodSecurityExpressionRoot.java
> +                .block();
SecurityExpressionRoot can't automatically subscribe to this Mono<Boolean> result

2023-03-30 13:26 UTC, merged