#56 Implement Jenkins
ilisau/qaprotours pull request #57
Opened 2023-04-17 12:15 UTC by ilisau

In this PR I implemented Jenkins for CI/CD and close #56

2023-04-19 07:56 UTC, ilisau commented
I have added Jenkinsfile and Jenkins with docker pods to cluster
Jenkins is also needed to be configured to use docker from another pod

2023-04-20 12:03 UTC, h1alexbel requested changes

2023-04-20 12:03 UTC, h1alexbel commented on .github/workflows/runner.yml
> +      - "*"
should be triggered only on `master` branch

In the case you simple pod listing you can do it on each `pull request` submitted to the `master` branch with your staging environment

2023-04-20 12:03 UTC, h1alexbel commented on src/infra/docker-deployment.yml
> +          image: docker:latest
use fixed versioning

2023-04-20 12:03 UTC, h1alexbel commented on src/infra/runner-serviceaccount.yml
> +---
split this config into multiple files

2023-04-21 08:04 UTC, h1alexbel approved these changes

2023-04-21 08:04 UTC, merged