#58 Implement Strimzi
ilisau/qaprotours pull request #59
Opened 2023-04-26 08:35 UTC by ilisau

In this PR I implemented Strimzi and close #58

2023-04-26 09:07 UTC, h1alexbel requested changes

2023-04-26 09:07 UTC, h1alexbel commented on kafka-setup.sh
> +kubectl apply -f https://strimzi.io/install/latest?namespace=kafka -n kafka
why is the latest one?

prefer fixed versions

2023-04-26 09:23 UTC, ilisau commented on kafka-setup.sh
> +kubectl apply -f https://strimzi.io/install/latest?namespace=kafka -n kafka
they have only latest tag accessible by fetching from url

2023-04-26 11:17 UTC, h1alexbel commented on kafka-setup.sh
> +kubectl apply -f https://strimzi.io/install/latest?namespace=kafka -n kafka
fix it, we need to use only prefixed versions

2023-04-26 12:54 UTC, h1alexbel requested changes

2023-04-26 12:54 UTC, h1alexbel commented on kafka-setup.sh
> +kubectl apply -f https://strimzi.io/examples/0.34.0/kafka/kafka-persistent-single.yaml -n kafka
@ilisau I got this error after applying it:
`unable to read URL "https://strimzi.io/install/0.34.0?namespace=kafka", server reported 404 Not Found, status code=404`

2023-04-27 15:08 UTC, h1alexbel approved these changes

2023-04-27 15:08 UTC, merged