Implement tests
ilisau/qaprotours pull request #62
Opened 2023-05-02 13:18 UTC by ilisau

In this PR I implemented tests

2023-05-03 09:44 UTC, h1alexbel reviewed
@ilisau pull request is too large, hard to review it

2023-05-03 09:44 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/AuthServiceTests.java
> +    void loginWithIncorrectPassword() {
@ilisau avoid those long tests. [read](https://www.yegor256.com/2017/05/17/single-statement-unit-tests.html) about single-statement test technique

2023-05-03 09:44 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/ImageServiceTests.java
> +    private static InputStream generateImage() throws Exception {
@ilisau what is it?

2023-05-03 09:44 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/SchedulerTests.java
> +    void findNotConfirmedTickets() {
@ilisau absolutely unmaintainable tests, fix it.
also, consider [reading](https://www.yegor256.com/2018/12/11/unit-testing-anti-patterns.html) about test patterns and anti-patterns

2023-05-08 19:40 UTC, ilisau commented
@h1alexbel please review this PR

2023-05-09 09:16 UTC, h1alexbel requested changes

2023-05-09 09:16 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/SchedulerTests.java
> +        User user = generateUser();
the same

2023-05-10 06:55 UTC, ilisau commented on src/test/java/com/solvd/qaprotours/service/impl/AuthServiceTests.java
> +import static org.mockito.ArgumentMatchers.any;
default imports are not available there

2023-05-10 09:16 UTC, h1alexbel requested changes

2023-05-10 09:16 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/AuthServiceTests.java
> +        when(passwordEncoder.matches(
@ilisau static imports should be removed

2023-05-15 14:11 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/AuthServiceTests.java
> +        User user = generateUser();
@ilisau you don't need to mock inside the service logic using Mockito or any other frameworks

you just need to obey your interface contract and return something fake
this is the main idea behind fake objects

2023-05-16 10:28 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/security/SecurityConfig.java
> +                .anyRequest().permitAll()
@ilisau I think the actuator endpoints need to be hidden from anonymous accounts, and only users with role `ADMIN` have ability to use those endpoints

WDYT?

2023-05-16 10:28 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/AuthServiceTests.java
> +        Mockito.when(userClient.getByEmail(authentication.getEmail()))
@ilisau why do you need to mock your already "faked" dependencies?

Using fake objects all you need is to inject fakes into object under test

2023-05-16 10:33 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/security/SecurityConfig.java
> +                .anyRequest().permitAll()
@h1alexbel circuitbreaker calls this api to check whether service is alive, so it is complicated to generate tokens for this feature

2023-05-16 12:08 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/security/SecurityConfig.java
> +                .anyRequest().permitAll()
@ilisau yes, you are right, but how to make this endpoint hidden from other users?

2023-05-16 12:09 UTC, h1alexbel commented
> Spring does not inject dependencies anyway in tests. And in some tests I need to mock repositories to interact with them. Otherwise, if I use `@Mock` and fake service without `Mockito.when(...)` it returns null in all methods, not what it actually should return in implemented fake services

Mocking the repositories is OK

2023-05-16 12:26 UTC, h1alexbel approved these changes
@ilisau a little more maintainable)

2023-05-16 12:26 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/AuthServiceTests.java
> +    @MockBean
@ilisau nice

2023-05-16 12:26 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/service/impl/AuthServiceTests.java
> +        Mockito.when(jwtService.isTokenType(ArgumentMatchers.anyString(), ArgumentMatchers.eq(JwtTokenType.RESET)))
@ilisau So, here you're mocking only jwt service

2023-05-16 12:29 UTC, h1alexbel approved these changes

2023-05-16 13:16 UTC, h1alexbel approved these changes

2023-05-16 13:26 UTC, ilisau commented
@h1alexbel So now I need to create repositories` beans, because I also need to create tested services beans

2023-05-16 14:26 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/config/TestConfig.java
> +                24,
@ilisau what is the 24?

2023-05-16 14:26 UTC, h1alexbel commented on src/test/java/com/solvd/qaprotours/config/TestConfig.java
> +        return null;
@ilisau don't return NULL

avoid this technique at all costs

2023-05-16 14:27 UTC, ilisau commented on src/test/java/com/solvd/qaprotours/config/TestConfig.java
> +                24,
time constants from application.yml

2023-05-17 09:22 UTC, merged