#63 Implement checkstyle
ilisau/qaprotours pull request #64
Opened 2023-05-03 17:25 UTC by ilisau

In this PR I implemented checkstyle checks and refactored classes to follow it and close #63

2023-05-03 17:30 UTC, ilisau commented
checks are failed because of tests are written in another branch but with the same check limits in pom.xml

2023-05-04 15:41 UTC, h1alexbel requested changes

2023-05-04 15:41 UTC, h1alexbel commented on checkstyle-suppressions.xml
> +    <suppress checks="MissingJavadocMethod"/>
@ilisau should be enabled

2023-05-04 15:41 UTC, h1alexbel commented on checkstyle-suppressions.xml
> +    <suppress checks="JavadocPackage"/>
@ilisau should be enabled

2023-05-04 15:41 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/tour/Tour.java
>      @Embedded
@ilisau hibernate non-reactive can't be used with project reactor.
consider using database drivers with reactive support or use non-reactive approach with hibernate

2023-05-04 15:41 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/repository/TicketRepository.java
> +    findAllByTourArrivalTimeIsAfterAndTourArrivalTimeIsBeforeAndStatus(
@ilisau naming should be fixed

2023-05-04 15:41 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/JwtServiceImpl.java
> +    private String generateRefreshToken(final User user) {
@ilisau `private` methods should be replaced with new classes.

2023-05-04 15:41 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/UserClientImpl.java
> +                .uri("http://user-client/api/v1/users/"
@ilisau `uri` should be pasted here from env config, don't hardcode it

2023-05-04 15:41 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/kafka/MessageSender.java
> +    Flux<SenderResult<MailDataDto>> sendMessage(String topic,
too many args

@ilisau WDYT?

2023-05-04 16:17 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/kafka/MessageSender.java
> +    Flux<SenderResult<MailDataDto>> sendMessage(String topic,
I think that 4 of them is not bad because I need to specify topic and partition for message, so I can avoid `key` argument by setting it as `MailDataDto data``s hashcode

2023-05-04 16:34 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/kafka/MessageSender.java
> +    Flux<SenderResult<MailDataDto>> sendMessage(String topic,
@ilisau what's about grouping objects ?

2023-05-04 16:53 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/kafka/MessageSender.java
> +    Flux<SenderResult<MailDataDto>> sendMessage(String topic,
@h1alexbel I can create a shell object that only contains topic, partition and key, but it will move a lot of params problem to previous layer when this method is called

2023-05-04 17:03 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/kafka/MessageSender.java
> +    Flux<SenderResult<MailDataDto>> sendMessage(String topic,
It's better.
It's better to create object with 3-4 parameters rather than have a method which requires those parameters. 
@ilisau WDYT?

2023-05-05 11:37 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/controller/GlobalExceptionHandler.java
> +    public ErrorDto handleException(final Exception e) {
@ilisau  you can try `eo-cqrs/eo-rs`, small library for representing error in data formats like JSON, etc

2023-05-05 11:37 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/mapper/ImageMapper.java
>  public interface ImageMapper {
@ilisau you can try to use Generic interface for mapping logic.
Like this:
```java
interface Mappable<X, Y> {
X toX(Y y);

Y toY(X x); 
}
```
WDYT?

2023-05-05 12:07 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/mapper/ImageMapper.java
>  public interface ImageMapper {
@h1alexbel now all mappers have the same methods so I can create it and implement

2023-05-10 06:52 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/controller/GlobalExceptionHandler.java
> +    public ErrorDto handleException(final Exception e) {
I need inner field that represents a map of fields with errors (in case of failed validation in controller)

2023-05-10 06:58 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/controller/GlobalExceptionHandler.java
> +    public ErrorDto handleException(final Exception e) {
I need inner map that can represent validation errors with field and error message

2023-05-10 09:30 UTC, h1alexbel approved these changes

2023-05-10 09:34 UTC, merged