#60 Implement Elasticsearch
ilisau/qaprotours pull request #65
Opened 2023-05-10 13:49 UTC by ilisau

In this PR I implemented Elasticsearch to save Tour objects to it via Kafka and close #60

2023-05-12 11:35 UTC, ilisau commented
@h1alexbel This pr also does not contain tests for check

2023-05-12 14:38 UTC, h1alexbel requested changes

2023-05-12 14:38 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +import com.solvd.qaprotours.web.kafka.KafkaMessage;
@ilisau why package `kafka` is located in the package `web`?

2023-05-12 14:38 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
>      private static final int PAGE_SIZE = 20;
static fields goes up

2023-05-12 14:38 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +                    message.setData(null);
@ilisau why data is `NULL`?

2023-05-12 14:38 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/kafka/KfConsumerConfig.java
> +        props.put(
@ilisau you can create an object, that represents the config itself like just a list of properties and then transform this list to the actual map that you needed here

thus, logic will be more scalable to settings changes

WDYT?

2023-05-12 14:38 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/security/SecurityConfig.java
> +//@EnableGlobalMethodSecurity(prePostEnabled = true)
comments should be removed

2023-05-12 14:38 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/security/SecurityConfig.java
> +//@EnableWebSecurity
the same here

2023-05-12 14:38 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/web/kafka/MessageReceiverImpl.java
> +    private final IndexHandler indexHandler;
@ilisau more handlers you will have -> bigger dependency list will be owned by your MessageReceiver

you can inject all the handlers into one simple map and then get the related to fetched  record, handler

it will be more maintainable, and far more reusable

WDYT?

2023-05-13 08:20 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +                    message.setData(null);
@h1alexbel Data field represents TourDto object to be sent to ES, in this method there is nothing of such type, so handler gets empty data field and does not interact with it, just take tourId from message`s key

2023-05-13 08:28 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/web/kafka/KfConsumerConfig.java
> +        props.put(
@h1alexbel I can create a bean with only `Map<String, Object>` inside, so it would be an individual bean, but also all my props are stored in XML file and accessed from it.

2023-05-13 11:46 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +                    message.setData(null);
@ilisau ok, reasonable

2023-05-13 12:23 UTC, ilisau commented
@h1alexbel so now can PR me merged?

2023-05-15 09:21 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/config/kafka/KfConsumerConfig.java
> +    public Map<String, Object> receiverProps() {
@ilisau you can try `eo-cqrs/eo-kafka`
using Object called `KfXmlFlexible`:
```java
@Bean
public KafkaConsumer<K, X> () {
return new KfXmlFlexible<K, X>("consumer.xml")
            .consumer();
}            
```

thus you can directly and transparently create consumers/producers by just changing an XML file

P.S Unfortunately, you are creating Reactive Kafka Producers and Consumers, so you can't create something as simple as 
non-reactive KafkaConsumer/KafkaProducer

2023-05-15 09:21 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/config/kafka/elasticsearch/HandlersMap.java
> +public class HandlersMap implements Handler {
@ilisau why do you need this?

2023-05-15 09:37 UTC, h1alexbel commented
> @h1alexbel so now can PR me merged?

we can't, since quality gate is failing

2023-05-15 10:33 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/config/kafka/KfConsumerConfig.java
> +    public Map<String, Object> receiverProps() {
@h1alexbel so `eo-cqrs/eo-kafka` can't help me with it?

2023-05-15 10:55 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/config/kafka/KfConsumerConfig.java
> +    public Map<String, Object> receiverProps() {
@ilisau yes, since it doesn't contain logic for reactive clients creation

2023-05-15 11:02 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/config/kafka/KfConsumerConfig.java
> +    public Map<String, Object> receiverProps() {
@ilisau by the way I created ticket for this, maybe we can implement this feature in the future

2023-05-15 11:17 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/config/kafka/elasticsearch/HandlersMap.java
> +public class HandlersMap implements Handler {
I have not know about such functionality, so thank you and I will implement this

2023-05-15 14:03 UTC, ilisau commented on src/main/java/com/solvd/qaprotours/config/kafka/MessageReceiverImpl.java
> +                .subscribe(r -> {
@h1alexbel I fixed it now. I check if body exists, then object is indexed, if not and key ends with '_delete' then object is going to be deleted

2023-05-16 11:55 UTC, h1alexbel requested changes

2023-05-16 11:55 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/config/kafka/elasticsearch/IndexHandler.java
> +                log.warn("Request is not sent because of exception: "
@ilisau it's better to re-throw exception instead of logging it

2023-05-17 11:45 UTC, ilisau commented
So codecov patch and project tries to check all lines coverage that is not useful (i have models, controllers and repositories that have no sense to be covered by tests)

2023-05-17 12:51 UTC, ilisau commented
@h1alexbel of course we can, but all my controllers are just mapping objects and call services and also i dont have an implementation of repositories so I cant to test them
I think that this testing approach as in Codecov is too much for this project because of all core logic is in one package and it is not useful

2023-05-17 12:52 UTC, h1alexbel commented
@ilisau do integration testing with your repos

2023-05-22 13:33 UTC, h1alexbel requested changes

2023-05-22 13:33 UTC, h1alexbel commented on .github/workflows/codecov.yml
> +        # advanced settings
@ilisau remove comments

2023-05-22 13:37 UTC, h1alexbel approved these changes
@ilisau very nice

2023-05-22 13:37 UTC, merged