#66 Implement ElasticSearch accessing
ilisau/qaprotours pull request #68
Opened 2023-05-19 12:15 UTC by ilisau

2023-05-19 13:57 UTC, h1alexbel requested changes

2023-05-19 13:57 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
>   * @author Varya Petrova, Lisov Ilya
@ilisau each author should be placed from new line

2023-05-19 13:57 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +
remove empty lines

2023-05-19 13:57 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +
the same here

2023-05-19 13:57 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/TourServiceImpl.java
> +    private List<Tour> getAllByCriteria(final TourCriteria tourCriteria,
this method is an absolute monster, unmaintainable
simply if you want to add new fields to criteria - you will need to change this method
make it through objects

each field can be applied to criteria through `apply()` method
like this: 

```java
interface Field {
void apply();

class Country implements Field {
}
etc...
```

so, each field will be applied in a declarative way
now, if you want to add/remove fields in criteria you will add/remove field object into object chain

2023-05-19 13:57 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/service/impl/fake/FakeTourService.java
> +        Mono<Tour> tour1 = getById(1L);
give better names for your variables

2023-05-19 22:01 UTC, ilisau commented
So I need to do smth like this or maybe store all criteria in another form?

2023-05-22 09:19 UTC, h1alexbel requested changes

2023-05-22 09:19 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/field/ArrivalTimeField.java
> +public class ArrivalTimeField implements Field {
@ilisau you can simplify class name
just remove `Field` suffix

2023-05-22 09:19 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/field/CountryField.java
> +public class CountryField implements Field {
the same here

2023-05-22 09:19 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/field/DayDurationField.java
> +public class DayDurationField implements Field {
the same here

2023-05-22 09:19 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/field/TourTypeField.java
> +public class TourTypeField implements Field {
the same here

2023-05-22 09:19 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/tour/TourCriteria.java
> +    private CountryField country;
@ilisau try `List<Field>`

2023-05-22 09:19 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/tour/TourCriteria.java
> +        country = new CountryField();
@ilisau looks so unflexible

use List of fields

2023-05-22 09:19 UTC, h1alexbel commented on src/main/java/com/solvd/qaprotours/domain/tour/TourCriteria.java
> +        this.country.apply(searchQuery);
@ilisau obvious code duplication, adding more fields your method will grow

2023-05-22 10:15 UTC, ilisau commented
@h1alexbel I need to map fields somewhere, because, as I explored, Mapstruct can't do it by itself

2023-05-22 11:00 UTC, h1alexbel requested changes

2023-05-22 11:23 UTC, h1alexbel approved these changes

2023-05-22 11:23 UTC, h1alexbel commented
@ilisau nice

2023-05-22 11:24 UTC, merged